#!/bin/bash
#
#-errorgrab v2.0.1
#-A script to grab errors from message files
#
#- in development:
#- find logspam, multiple
#
#

#startup function
function startup (){
echo "**************************************"
echo "**        errorgrab v. 2.0.1        **"
echo "**************************************"
echo ""
echo "Checking current directory..."

username="$(whoami)"

echo "Hello $username"

loc="$(pwd)"

echo "Our current location is $loc . Is this the root of the logset? (y/n)"
read atroot

if [ "$atroot" = "y" ]
then
  MAINF
else
  echo "Please re-run this script from the root of the logset"
  exit 0
fi
} #end startup


#message search
function message_search(){
  echo "Looking for messages logs..."

  $(cd ./messages)


  echo "What are you searching for? (case insensitive)"
  read searchby

  echo "How far back would you like to search? (date format YYYY-MM-DD, format can be a fragmnet like YYYY-MM or YYYY)"
  read timeframe

  echo "Would you like to output the results to a file? (y/n)"
  read writefile

  if [ $writefile = "y" ]
  then
    myfilename="messages_$(date +%m%d%Y)_$searchby"
    echo $myfilename
  fi

  #list="$loc/*"

  #OIFS=$IFS

  #IFS='\n'
  FILECOUNT="$(ls $loc | grep -v ^l | wc -l)"


  FILELIST=("$(ls $loc | sort -V)")


  echo "There are $FILECOUNT files in $loc" 

  echo "The search param is $searchby"

  if [ $writefile = "y" ]
  then

    for x in $FILELIST
      do
      echo "----------------------------------------------------" >> $myfilename
      echo "$x  Search parameter: $searchby" >> $myfilename
      echo "----------------------------------------------------" >> $myfilename
      result="$(grep -i $searchby $x | grep -i $timeframe | sort | uniq -f3)"
      echo "$result" >> $myfilename
      echo "" >> $myfilename
    done
    echo "Output has been written to $myfilename"
  else

    for x in $FILELIST
      do
      echo "----------------------------------------------------"
      echo "$x  Search parameter: $searchby"
      echo "----------------------------------------------------"
      result="$(grep -i $searchby $x | grep -i $timeframe | sort | uniq -f2)"
      echo "$result"
      echo ""
    done 
  fi



  $(cd $loc)
  #exit 0
  MAINF
} #end message file search

#main function
function MAINF(){
echo "What would you like to do?"
echo "1 - Perform search of messages files"
echo "2 - this is option two"
echo "3 - this is option three"
read option

case "$option" in
  1)
    message_search
    ;;
  2)
    echo ""
    echo "that functionality isn't quite ready yet"
    echo ""
    MAINF
    ;;
  *)
    echo ""
    echo "please pick a valid option"
    echo ""
    MAINF
    ;;
esac


}
#end main

startup
