#!/bin/bash
#
#-errorgrab v2.0
#-A script to grab errors from message files
#
#- in development:
#- find logspam, multiple
#
#
echo "**************************************"
echo "**        errorgrab v. 2.0          **"
echo "**************************************"

echo "What are you searching for? (case insensitive)"
read searchby

echo "How far back would you like to search? (date format YYYY-MM-DD, format can be a fragmnet like YYYY-MM or YYYY)"
read timeframe

loc="$(pwd)"

echo $loc

#list="$loc/*"

#OIFS=$IFS

#IFS='\n'
FILECOUNT="$(ls $loc | grep -v ^l | wc -l)"


FILELIST=("$(ls $loc | sort -V)")


echo "There are $FILECOUNT files in $loc"

echo "The search param is $searchby"

for x in $FILELIST
do
   #echo "Processing $x"
   echo "----------------------------------------------------"
   echo "$x  Search parameter: $searchby"
   echo "----------------------------------------------------"
   result="$(grep -i $searchby $x | grep -i $timeframe | sort | uniq -f2)"
   echo "$result"
   echo ""
done 



exit 0

for y in ${filenames[@]}
do
  echo "Processing ${filenames[$y]}"

done

#IFS=$OIFS
